// <auto-generated />
using System;
using Flight.Service.UserManagementAPI.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flight.Service.UserManagementAPI.Migrations
{
    [DbContext(typeof(LoginUserDbContext))]
    [Migration("20220530094315_loginusermigration")]
    partial class loginusermigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flight.Service.UserManagementAPI.Model.LoginTbl", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.HasKey("guid");

                    b.ToTable("loginTbls");
                });

            modelBuilder.Entity("Flight.Service.UserManagementAPI.Model.UserRoleTbl", b =>
                {
                    b.Property<int>("roleid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("guid");

                    b.Property<string>("rolename");

                    b.HasKey("roleid");

                    b.ToTable("userRoleTbls");
                });
#pragma warning restore 612, 618
        }
    }
}
